<article>
<article_id></article_id>
<articletitle></articletitle>
<articledatefrom></articledatefrom>
<articledateto></articledateto>
<articlestatus>active</articlestatus>
<articleuser></articleuser>
<articletextcollection>
</articletextcollection>
<articlemediacollection>
</articlemediacollection>
<articlelinkcollection>
</articlelinkcollection>
<articlecomponentcollection>
</articlecomponentcollection>
</article>