<media>
<media_id></media_id>
<mediauser></mediauser>
<mediafile></mediafile>
<mediaobject></mediaobject>
<mediaalttext></mediaalttext>
<mediaalign></mediaalign>
<mediawidth></mediawidth>
<mediaheight></mediaheight>
</media>