/*
 Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
var selectList_cache;function iterationChange(k){var f=k.ownerDocument,h=f.getElementById("rmAfterLoadSpan"),f=f.getElementById("rmAfterLoadInput");"0"===k.value?(h.style.color="lightgrey",f.disabled=!0):(h.style.color="black",f.disabled=!1)}
function animSelectionChange(k){var f=CKEDITOR.plugins.cssanim.ckEditor.lang.cssanim,h=k.parentElement.parentElement,n=h.parentNode.parentNode.parentNode.getElementsByClassName("cssAnimButton"),l=k.ownerDocument,m=l.getElementById("rmAfterLoadSpan"),d=l.getElementById("rmAfterLoadInput"),e=l.getElementsByName("anim_L").item(0),b=l.getElementsByName("anim_C").item(0),l=l.getElementsByName("anim_O").item(0);if("anim_L"===k.name&&"none"===e.value){if("cssAnimPause"===b.value){alert(f.pbOnClickPause);
e.selectedIndex=selectList_cache;return}if("cssAnimPause"===l.value){alert(f.pbOnOverPause);e.selectedIndex=selectList_cache;return}}if("anim_C"===k.name&&"none"===e.value&&"cssAnimPause"===b.value)alert(f.pbOnClickOnLoadNone),b.selectedIndex=selectList_cache;else if("anim_O"===k.name&&"none"===e.value&&"cssAnimPause"===l.value)alert(f.pbOnOverOnLoadNone),l.selectedIndex=selectList_cache;else if("cssAnimPause"===k.value||"none"===k.value){for(f=1;f<h.childElementCount;f+=1)h.childNodes[f].style.opacity=
0;n[0].style.display="none";"anim_L"===k.name&&(m.style.color="lightgrey",d.disabled=!0)}else{for(f=1;f<h.childElementCount;f+=1)h.childNodes[f].style.opacity="initial";n[0].style.display="initial";"anim_L"===k.name&&(m.style.color="black",d.disabled=!1)}}
CKEDITOR.dialog.add("cssanimAddAnimDialog",function(k){function f(d,e,b,c){var a="",f='checked \x3d "checked"',k=0,l="normal",m=1,q=1,n="none",w="linear",t=["linear","ease","ease-in","ease-out","ease-in-out"],u=["normal","alternate"],g=null,g="",g="black";c&&(0<=c.indexOf("animation-play-state")?g={name:"cssAnimPause",duration:null,timingFunction:"linear",delay:0,iterationCount:1,direction:"normal"}:(k=c.replace("{animation:","").replace("}","").replace(";","").trim(),g=parseCSS3AnimationShorthand(k)),
k=g.delay/1E3,l=g.direction,m=g.duration/1E3,q=g.iterationCount,"infinite"===q&&(q=0,b=!1),n=g.name,w=g.timingFunction);var a=a+'\x3ctable style\x3d"display:block; overflow-y\x3dscroll; height: 75px; overflow-y: auto; width:550px;"\x3e\x3ctr\x3e',a=a+'\x3cth style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px; width:100px;"\x3e',a=a+h.name,a=a+"\x3c/th\x3e",a=a+'\x3cth style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px; width:60px;"\x3e',
a=a+h.duration,a=a+"\x3c/th\x3e",a=a+'\x3cth style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px; width:100px;"\x3e',a=a+h.tFunc,a=a+"\x3c/th\x3e",a=a+'\x3cth style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px; width:60px;"\x3e',a=a+h.delay,a=a+"\x3c/th\x3e",a=a+'\x3cth title\x3d"If set to 0, iteration will be set as \'infinite\'" style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px; width:70px;"\x3e',a=a+
h.iter,a=a+"\x3c/th\x3e",a=a+'\x3cth style\x3d"text-align: center;font-weight: bold;border: 1px solid grey;padding: 2px;"\x3e',a=a+h.direction,a=a+"\x3c/th\x3e",a=a+"\x3c/tr\x3e",a=a+"\x3ctr\x3e",a=a+'\x3ctd style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e',p,g="";"none"===n&&(g="selected");c=""+('\x3cselect  onclick\x3d"selectList_cache\x3dthis.selectedIndex" onChange\x3d"animSelectionChange(this);" name\x3d"anim'+e+'"\x3e')+('\x3coption value\x3d"none" '+g+"\x3e"+h.none+
"\x3c/option\x3e");"_L"!==e&&(g="","cssAnimPause"===n&&(g="selected"),c+='\x3coption value\x3d"cssAnimPause" '+g+"\x3e"+h.cssAnimPause+"\x3c/option\x3e");var v,r;for(v in d){r=d[v];c+='\x3coptgroup label\x3d"'+v+'" style\x3d"font-weight:bold"\x3e';for(p=0;p<r.length;p+=1)g="",r[p]===n&&(g="selected"),c+='\x3coption value\x3d"'+r[p]+'" '+g+"\x3e"+r[p]+"\x3c/option\x3e";c+="  \x3c/optgroup\x3e"}c+="\x3c/select\x3e";a+=c;a+="\x3c/td\x3e";a+='\x3ctd style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e';
a+='\x3cinput name\x3d"duration'+e+'" type\x3d"number" min\x3d"1" max\x3d"600" value\x3d"'+m+'" style\x3d"width:4em; border:1px solid gainsboro;"\x3esec';a+="\x3c/td\x3e";a+='\x3ctd style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e';a+='\x3cselect name\x3d"timing'+e+'" style\x3d"border:1px solid gainsboro;"\x3e';for(d=0;d<t.length;d+=1)g="",t[d]===w&&(g="selected"),a+='\x3coption value\x3d"'+t[d]+'" '+g+"\x3e"+t[d]+"\x3c/option\x3e";a+="\x3c/select\x3e";a+="\x3c/td\x3e";
a+='\x3ctd style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e';a+='\x3cinput name\x3d"delay'+e+'" type\x3d"number" min\x3d"0" max\x3d"600" value\x3d"'+k+'" style\x3d"width:4em; border:1px solid gainsboro;"\x3esec';a+="\x3c/td\x3e";a+='\x3ctd title\x3d"If set to 0, iteration will be set as \'infinite\'" style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e';a+='\x3cinput name\x3d"iteration'+e+'" type\x3d"number" min\x3d"0" max\x3d"99" value\x3d"'+q+'" style\x3d"width:3em; border:1px solid gainsboro" onChange\x3d"iterationChange(this);"\x3e';
a+="\x3c/td\x3e";a+='\x3ctd style\x3d"text-align: center;padding: 3px;border: 1px solid gainsboro;"\x3e';a+='\x3cselect name\x3d"direction'+e+'" style\x3d"border:1px solid gainsboro;"\x3e';for(d=0;d<u.length;d+=1)g="",u[d]===l&&(g="selected"),a+='\x3coption value\x3d"'+u[d]+'" '+g+"\x3e"+u[d]+"\x3c/option\x3e";a+="\x3c/select\x3e";a+="\x3c/td\x3e";a+="\x3c/tr\x3e";g="black";null!==b&&(!1===b&&(f=""),0===q&&(f="disabled",g="lightgrey"),a+="\x3ctr\x3e",a+='\x3ctd colspan\x3d"3" style\x3d"text-align: center;padding: 3px; border-left: 1px solid gainsboro; border-bottom: 1px solid gainsboro;"\x3e',
a+='\x3cspan id\x3d"rmAfterLoadSpan" style\x3d"color:'+g+'" title\x3d"'+h.ralTitle+'"\x3e'+h.ral+"\x3c/span\x3e",a+="\x3c/td\x3e",a+='\x3ctd colspan\x3d"3" style\x3d"text-align: left; padding: 3px;  border-right: 1px solid gainsboro; border-bottom: 1px solid gainsboro;"\x3e',a+='\x3cinput  id\x3d"rmAfterLoadInput" type\x3d"checkbox" name\x3d"rmAfterLoad"  '+f+"\x3e",a+="\x3c/td\x3e",a+="\x3c/tr\x3e");return a+="\x3c/table\x3e"}var h=k.lang.cssanim,n=CKEDITOR.getUrl(CKEDITOR.plugins.get("cssanim").path+
"dialogs/css3animation.png"),l=null,m;return{title:h.editAnimsTitle,width:600,minWidth:600,height:400,minHeight:400,resizable:CKEDITOR.DIALOG_RESIZE_NONE,contents:[{id:"mainPanel",label:"CSS_Animation",title:"Animation",padding:0,elements:[{type:"html",id:"htmlAnim",html:"",setup:function(){var d=document.getElementById(this.domId),e=k.config.allowedAnimations;CKEDITOR.plugins.cssanim.runHighLightElem(l);var b=l,c=null,a;if(c=b.getAttribute("data-animation"))a=decodeURIComponent(c),c=JSON.parse(a),
CKEDITOR.plugins.cssanim.managePending&&(m[m.length]=[b.getId(),a]);b='\x3cdiv class\x3d"tabs" style\x3d"width:600px;"\x3e\x3cdiv class\x3d"tab"\x3e';b+='\x3cinput type\x3d"radio" id\x3d"tab-Over" name\x3d"tab-group-1" \x3e';b+='\x3clabel for\x3d"tab-Over"\x3eOnOver\x3c/label\x3e';b+='\x3cdiv id\x3d"cssanimAddAnimDialogTabOver" class\x3d"content" style\x3d"height:85px;"\x3e';a=c&&c.cdo?c.cdo:null;b+=f(e,"_O",null,a);b+='\x3cdiv style\x3d"text-align: center; padding: 5px;"\x3e';b+='\x3cinput type\x3d"button" class\x3d"cssAnimButton" value\x3d"'+
h.testIt+' !" name\x3d"overBtn" onclick\x3d"CKEDITOR.plugins.cssanim.cssanimAddAnimDialogTest(this);"\x3e';b+="\x3c/div\x3e ";b+="\x3c/div\x3e ";b+='\x3cdiv class\x3d"tab"\x3e';b+='\x3cinput type\x3d"radio" id\x3d"tab-Click" name\x3d"tab-group-1" \x3e';b+='\x3clabel for\x3d"tab-Click"\x3eOnClick\x3c/label\x3e';b+='\x3cdiv  id\x3d"cssanimAddAnimDialogTabClick" class\x3d"content" style\x3d"height:85px;"\x3e';a=c&&c.cdc?c.cdc:null;b+=f(e,"_C",null,a);b+='\x3cdiv style\x3d"text-align: center; padding: 5px;"\x3e';
b+='\x3cinput type\x3d"button" class\x3d"cssAnimButton" value\x3d"'+h.testIt+' !" name\x3d"clickBtn" onclick\x3d"CKEDITOR.plugins.cssanim.cssanimAddAnimDialogTest(this);"\x3e';b+="\x3c/div\x3e ";b+="\x3c/div\x3e ";b+='\x3cdiv class\x3d"tab"\x3e';b+='\x3cinput type\x3d"radio" id\x3d"tab-Load" name\x3d"tab-group-1" checked\x3e';b+='\x3clabel for\x3d"tab-Load"\x3eOnLoad\x3c/label\x3e';b+='\x3cdiv  id\x3d"cssanimAddAnimDialogTabLoad" class\x3d"content" style\x3d"height:85px;"\x3e';a=c&&c.cds?c.cds:null;
b+=f(e,"_L",c?c.ral:!0,a);b+='\x3cdiv style\x3d"text-align: center; padding: 5px;"\x3e';b+='\x3cinput type\x3d"button" class\x3d"cssAnimButton" value\x3d"'+h.testIt+' !" name\x3d"loadBtn" onclick\x3d"CKEDITOR.plugins.cssanim.cssanimAddAnimDialogTest(this);"\x3e';b+="\x3c/div\x3e ";b+="\x3c/div\x3e ";b+="\x3c/div\x3e";e='\x3clink rel\x3d"stylesheet" href\x3d"./ckeditor/plugins/cssanim/css/cssanim.css"\x3e\x3cstyle type\x3d"text/css"\x3e.cke_cssanim_container{color:#000 !important;padding:10px 10px 0;margin-top:5px;text-align: center;}.cke_cssanim_container p{margin: 0 0 10px;}\x3c/style\x3e\x3cdiv class\x3d"cke_cssanim_container"\x3e\x3cdiv class\x3d"cke_cssanim_container_div" style\x3d"text-align: center; border: 1px solid grey; width:50%;margin-left: auto;margin-right: auto;"\x3e\x3cimg class\x3d"cke_cssanim_container_img" src\x3d"'+
n+'" alt\x3d"CSS Animation" style\x3d"border: 1px solid grey; padding: 5px; margin: 10px;"\x3e\x3c/div\x3e\x3cbr\x3e\x3cbr\x3e\x3cp id\x3d"elemName" style\x3d"font-weight:bold;font-size: larger;text-align: -webkit-center;"\x3eAnimation '+h.forStr+" : "+l.getName()+"\x3c/p\x3e\x3cbr\x3e"+b+"\x3c/div\x3e";d.innerHTML=e;CKEDITOR.plugins.cssanim.cssanimAddAnimDialog=d},cancel:function(){CKEDITOR.plugins.cssanim.cleanHighlight()},commit:function(){CKEDITOR.plugins.cssanim.cleanHighlight();var d,e=this.getElement().getElementsByTag("input"),
b=this.getElement().getElementsByTag("select"),c={animStart:null,animClick:null,animOver:null,ral:!1};d=b.getItem("anim_L").getValue();"none"!==d&&(c.animStart=d+" ",c.animStart+=e.getItem("duration_L").getValue()+"s ",c.animStart+=b.getItem("timing_L").getValue()+" ",c.animStart+=e.getItem("delay_L").getValue()+"s ",d=e.getItem("iteration_L").getValue(),"0"===d&&(d="infinite"),c.animStart+=d+" ",c.animStart+=b.getItem("direction_L").getValue(),e.getItem("rmAfterLoad").$.checked&&"infinite"!==d&&
(c.ral=!0));d=b.getItem("anim_C").getValue();"none"!==d&&(c.animClick=d+" ",c.animClick+=e.getItem("duration_C").getValue()+"s ",c.animClick+=b.getItem("timing_C").getValue()+" ",c.animClick+=e.getItem("delay_C").getValue()+"s ",d=e.getItem("iteration_C").getValue(),"0"===d&&(d="infinite"),c.animClick+=d+" ",c.animClick+=b.getItem("direction_C").getValue());d=b.getItem("anim_O").getValue();"none"!==d&&(c.animOver=d+" ",c.animOver+=e.getItem("duration_O").getValue()+"s ",c.animOver+=b.getItem("timing_O").getValue()+
" ",c.animOver+=e.getItem("delay_O").getValue()+"s ",d=e.getItem("iteration_O").getValue(),"0"===d&&(d="infinite"),c.animOver+=d+" ",c.animOver+=b.getItem("direction_O").getValue());CKEDITOR.plugins.cssanim.runAddAnimElem(l,c)}}]}],onShow:function(){l=CKEDITOR.plugins.cssanim.curSelectedElement;CKEDITOR.plugins.cssanim.managePending&&(m=CKEDITOR.plugins.cssanim.pendingChanges);this.setupContent();var d=this.getContentElement("mainPanel","htmlAnim").getInputElement().getElementsByTag("select"),e;e=
d.getItem("anim_L");animSelectionChange(e.$);e=d.getItem("anim_C");animSelectionChange(e.$);e=d.getItem("anim_O");animSelectionChange(e.$)},onOk:function(){this.commitContent();CKEDITOR.plugins.cssanim.managePending&&(CKEDITOR.plugins.cssanim.pendingChanges=m,CKEDITOR.plugins.cssanim.refreshCssAnimDialogAnimationsTab())},onCancel:function(){this.foreach(function(d){d.cancel&&d.cancel.apply(d)})}}});