<?xml version="1.0" ?>
<container>
<hyperCMS>
<contentcontainer></contentcontainer>
<contentxmlschema></contentxmlschema>
<contentorigin></contentorigin>
<contentobjects></contentobjects>
<contentuser></contentuser>
<contentdate></contentdate>
<contentpublished></contentpublished>
<contentstatus></contentstatus>
<contentworkflow></contentworkflow>
</hyperCMS>
<head>
<pagetitle></pagetitle>
<pageauthor></pageauthor>
<pagedescription></pagedescription>
<pagekeywords></pagekeywords>
<pagecontenttype></pagecontenttype>
<pagelanguage></pagelanguage>
<pagerevisit></pagerevisit>
<pagetracking></pagetracking>
</head>
<textcollection>
</textcollection>
<mediacollection>
</mediacollection>
<linkcollection>
</linkcollection>
<componentcollection>
</componentcollection>
<articlecollection>
</articlecollection>
</container>