<user>
<login></login>
<password></password>
<hashcode></hashcode>
<admin>0</admin>
<nologon>0</nologon>
<userdate></userdate>
<realname></realname>
<email></email>
<phone></phone>
<signature></signature>
<language></language>
<timezone></timezone>
<theme>standard</theme>
<validdatefrom></validdatefrom>
<validdateto></validdateto>
<memberof>
<publication></publication>
<usergroup></usergroup>
</memberof>
</user>